### ISSUE TITLE
'NoneType' object is not iterable issue in project with new gCNV data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#564]
Several standard searches (including for SNVs/ Indels we typically do) are not working and are returning the error - 'NoneType' object is not iterable

Example of a regular search- https://seqr.broadinstitute.org/variant_search/results/dacb9d393abfc3814762c5cb22c005f0?page=1&sort=protein_consequence

Example of a SV search - https://seqr.broadinstitute.org/variant_search/results/fb16daa34fe3f7bca598d18095b58744?page=1&sort=protein_consequence

<img width="1353" alt="Screenshot 2023-08-22 at 4 18 44 PM" src="https://github.com/broadinstitute/seqr-loading-pipelines/assets/37872186/5051d89c-fcd0-43ee-9fcb-03dc9eb7ec34">

Seems to be affecting the [CMG_Wilkins-Haug_Exomes](https://seqr.broadinstitute.org/project/R0476_cmg_wilkins_haug_exomes/project_page) project only

**Comment by bpblanken** [comment]
Application log:
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/seqr/seqr/views/apis/variant_search_api.py", line 60, in query_variants_handler
    variants, total_results = query_variants(results_model, sort=sort, page=page, num_results=per_page,
  File "/seqr/seqr/utils/search/utils.py", line 190, in query_variants
    variants, total_results = _query_variants(
  File "/seqr/seqr/utils/search/utils.py", line 240, in _query_variants
    variant_results = backend_specific_call(get_es_variants, get_hail_variants)(
  File "/seqr/seqr/utils/search/elasticsearch/es_utils.py", line 296, in get_es_variants
    return es_search.search(page=page, num_results=num_results)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 573, in search
    return self._execute_multi_search(**search_kwargs)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 681, in _execute_multi_search
    parsed_responses = [self._parse_response(response) for response in responses]
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 681, in <listcomp>
    parsed_responses = [self._parse_response(response) for response in responses]
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 751, in _parse_response
    response_hits, response_total = self._parse_compound_het_response(response)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 969, in _parse_compound_het_response
    self._parse_compound_het_gene(gene_agg, compound_het_pairs_by_gene, family_unaffected_individual_guids)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 980, in _parse_compound_het_gene
    gene_variants = [self._parse_hit(hit) for hit in gene_agg['vars_by_gene']]
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 980, in <listcomp>
    gene_variants = [self._parse_hit(hit) for hit in gene_agg['vars_by_gene']]
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 765, in _parse_hit
    family_guids, genotypes = self._parse_genotypes(raw_hit, hit, index_family_samples, data_type)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 864, in _parse_genotypes
    genotypes[sample.individual.guid] = _get_field_values(genotype_hit, genotype_fields_config)
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 1559, in _get_field_values
    return {
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 1560, in <dictcomp>
    field_config.get('response_key') or format_response_key(field): _value_if_has_key(
  File "/seqr/seqr/utils/search/elasticsearch/es_search.py", line 1574, in _value_if_has_key
    return format_value(default_value if hit[key] is None else hit[key]) if format_value else hit[key]
TypeError: 'NoneType' object is not iterable
```
